
FROM ibmcom/informix-developer-database:12.10.FC12W1DE

ADD informix_inf.env /opt/ibm/scripts/informix_inf.env 
ADD informix_inf.env /usr/local/bin/informix_inf.env

RUN mkdir -p /opt/ibm/localdata

